<Project>
    <PropertyGroup>
        <Company>The Melding Wars</Company>
        <Product>Firefall DISASM Name Manager</Product>
        <Authors>The Melding Wars</Authors>
        <Copyright>Copyright © 2020-2026 The Melding Wars</Copyright>
        <NeutralLanguage>en-US</NeutralLanguage>
        <RepositoryUrl>https://github.com/themeldingwars/Firefall-DISASM-Name-Manager</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
</Project>
